version: '3.8'

services:
  # 메인 Mobile VLA 컨테이너
  mobile-vla:
    image: mobile_vla:pytorch-2.3.0-ros2-complete
    container_name: mobile_vla_system
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      # CUDA 라이브러리 마운트
      - /usr/local/cuda:/usr/local/cuda:ro
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      # ROS 워크스페이스 마운트
      - ./ROS_action:/workspace/vla/ROS_action
      # X11 디스플레이 (GUI 앱용)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # 데이터셋 디렉토리
      - ./mobile_vla_dataset:/workspace/vla/mobile_vla_dataset
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /workspace/vla
    command: bash
    depends_on:
      - ros-master

  # ROS Master 컨테이너 (선택적)
  ros-master:
    image: ros:humble-ros-base
    container_name: ros_master
    environment:
      - ROS_DOMAIN_ID=0
    ports:
      - "11311:11311"
    command: roscore
    restart: unless-stopped

  # 개발용 컨테이너 (디버깅/개발용)
  mobile-vla-dev:
    image: mobile_vla:pytorch-2.3.0-ros2-complete
    container_name: mobile_vla_dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    volumes:
      - /usr/local/cuda:/usr/local/cuda:ro
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      - ./ROS_action:/workspace/vla/ROS_action
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./mobile_vla_dataset:/workspace/vla/mobile_vla_dataset
      # 개발용 추가 볼륨
      - ./scripts:/workspace/vla/scripts
      - ./logs:/workspace/vla/logs
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /workspace/vla
    command: bash
    profiles:
      - dev

  # 테스트용 컨테이너
  mobile-vla-test:
    image: mobile_vla:pytorch-2.3.0-ros2-complete
    container_name: mobile_vla_test
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
    volumes:
      - /usr/local/cuda:/usr/local/cuda:ro
      - /usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:ro
      - ./ROS_action:/workspace/vla/ROS_action
      - ./mobile_vla_dataset:/workspace/vla/mobile_vla_dataset
      - ./tests:/workspace/vla/tests
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /workspace/vla
    command: bash
    profiles:
      - test

networks:
  default:
    name: mobile_vla_network
