version: '3.8'

services:
  mobile-vla-system:
    build:
      context: .
      dockerfile: Dockerfile.mobile-vla
    container_name: mobile-vla-container
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/workspace/vla/ROS_action/src
      - ./mobile_vla_dataset:/workspace/vla/mobile_vla_dataset
      - ~/.cache/huggingface:/root/.cache/huggingface
    network_mode: host
    runtime: nvidia
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    privileged: true
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        cd /workspace/vla/ROS_action &&
        colcon build --packages-select mobile_vla_package &&
        source install/setup.bash &&
        ros2 launch mobile_vla_package launch_mobile_vla.launch.py inference_node:=true
      "
    restart: unless-stopped
