#!/bin/bash
# Billy Server Connection Info (SAFE VERSION - for Git)
# 실제 비밀 정보는 secrets.sh에 저장되어 있습니다.

echo "=================================================="
echo "🔒 Billy Server Security Configuration"
echo "=================================================="
echo ""
echo "📌 접속 정보는 로컬 secrets.sh에 저장되어 있습니다."
echo "   (Git에는 올라가지 않습니다)"
echo ""
echo "=================================================="
echo "Billy 서버 관리자용 명령어:"
echo "=================================================="
echo ""
echo "1. 서버 시작:"
echo "   source secrets.sh && python3 api_server.py"
echo ""
echo "2. 방화벽 설정 (처음 한 번만):"
echo "   sudo ./setup_security.sh"
echo ""
echo "3. 서버 상태 확인:"
echo "   lsof -i :8000"
echo ""
echo "=================================================="
echo "Jetson 담당자용 정보:"
echo "=================================================="
echo ""
echo "Jetson 설정은 'jetson_setup_template.sh'를 참고하세요."
echo "실제 IP와 API Key는 Billy 관리자에게 별도로 받으세요."
echo ""
echo "=================================================="
